### ISSUE TITLE
Pose Keypoint Extraction model notebook - invalid JSON formatting

### ISSUE THREAD

**Issue by Aristarkh4** [aws-samples/aws-media-replay-engine-samples#1]
The model-deployment notebook for Pose Keypoint Extraction (`aws-media-replay-engine-samples/source/mre-model-samples/Models/PoseKeypointsExtractionModel/PoseKeypointsExtractionModel.ipynb`) fails to load due to invalid JSON formatting.

There's a `,` missing between two blocks of the notebook.

**Comment by curvelets** [comment]
Hi @Aristarkh4 The PosekeypointsExtractionModel notebook has been updated with entrypoint.py. Please pull the latest version. Thanks
