### ISSUE TITLE
No appropriate Segmenter class for DetectFaces

### ISSUE THREAD

**Issue by raban33** [aws-samples/aws-media-replay-engine-samples#3]
Using MRE Console, when creating a profile there doesn't seem to be right Segmenter Plugin that can be applied for DetectFaces featurer plugin. Since this is a mandatory field, I had set it up to SegmentBySceneWithOffset which then has a dependency on DetectShotsByRekognitionVideo, When the event is scheduled with this profile and streaming has been configured with MediaLive Channel, the even completes without any results. When looked at the step function's error log, I see the below error. Any help to fix this would be appreciated.

{
  "errorMessage": "{'Error': 'Runtime.ImportModuleError', 'Cause': '{\"errorMessage\":\"Unable to import module \\'DetectShotsByRekognitionVideo\\': No module named \\'ffmpeg\\'\",\"errorType\":\"Runtime.ImportModuleError\",\"stackTrace\":[]}'}",
  "errorType": "MREExecutionError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 68, in lambda_handler\n    raise MREExecutionError(event[\"Error\"])\n"
  ]
}

**Comment by araviraj-aws** [comment]
As mentioned in the related issue (https://github.com/awslabs/aws-media-replay-engine/issues/5), plugin dependencies such as FFMPEG lambda layers are to be manually created and included in the Lambda function by plugin developers before invoking the plugin or running an MRE event.
